[2024-01-12T20:14:59.507+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG-1.print_the_context manual__2024-01-12T18:14:49.955811+00:00 [queued]>
[2024-01-12T20:14:59.512+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG-1.print_the_context manual__2024-01-12T18:14:49.955811+00:00 [queued]>
[2024-01-12T20:14:59.512+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T20:14:59.524+0200] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): print_the_context> on 2024-01-12 18:14:49.955811+00:00
[2024-01-12T20:14:59.529+0200] {standard_task_runner.py:60} INFO - Started process 16459 to run task
[2024-01-12T20:14:59.536+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'DAG-1', 'print_the_context', 'manual__2024-01-12T18:14:49.955811+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/angel_test.py', '--cfg-path', '/var/folders/4w/cqlcl4gn3lz6wkw0qjydjq9c0000gq/T/tmprzpq_qoo']
[2024-01-12T20:14:59.541+0200] {standard_task_runner.py:88} INFO - Job 18: Subtask print_the_context
[2024-01-12T20:14:59.588+0200] {task_command.py:423} INFO - Running <TaskInstance: DAG-1.print_the_context manual__2024-01-12T18:14:49.955811+00:00 [running]> on host TLV-02DN0GXP3YW
[2024-01-12T20:14:59.650+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='DAG-1' AIRFLOW_CTX_TASK_ID='print_the_context' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T18:14:49.955811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T18:14:49.955811+00:00'
[2024-01-12T20:15:01.060+0200] {logging_mixin.py:188} INFO - ('information_schema',)
[2024-01-12T20:15:01.068+0200] {logging_mixin.py:188} INFO - ('mydatabase',)
[2024-01-12T20:15:01.074+0200] {logging_mixin.py:188} INFO - ('mysql',)
[2024-01-12T20:15:01.077+0200] {logging_mixin.py:188} INFO - ('performance_schema',)
[2024-01-12T20:15:01.080+0200] {logging_mixin.py:188} INFO - ('sys',)
[2024-01-12T20:15:16.406+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/angel.georgiev/airflow/dags/angel_test.py", line 53, in print_context
    conn = pyodbc.connect(connection_string)
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
[2024-01-12T20:15:16.416+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=DAG-1, task_id=print_the_context, execution_date=20240112T181449, start_date=20240112T181459, end_date=20240112T181516
[2024-01-12T20:15:16.426+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task print_the_context (('HYT00', '[HYT00] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0) (SQLDriverConnect)'); 16459)
[2024-01-12T20:15:16.464+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T20:15:16.482+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
